### ISSUE TITLE
Feature request: save to/load from .wav file

### ISSUE THREAD

**Issue by PFython** [jvmeifert/afskmodem#8]
Hi - first of all thanks so much for all the effort you've put into this so far.  I stumbled on it recently after getting into HAM radio and want to try using Python for various things... including a 'modem' setup between two handsets.

Anyway... I'm not familiar with pyaudio yet and just wondered if you might be able to quickly/easily add an option to save the transmit audio as a .wav file instead of immediately sending it to default audio?

Likewise the ability to load a .wav file and rinse it through the receiver?

This would be an awesome addition to the module but I appreciate your time is valuable and if it's a hassle you probably have better things to do!  If you're up for the challenge, though, I think it would be a worthwhile enhancement.

Thanks again for your time and consideration,
Pete

**Comment by lavajuno** [comment]
Thank you for the kind words, it's great to see that this project is something that people can make use of.
I'd be happy to add functionality to import & export from WAV files. It should be pretty straightforward, so I can't imagine it taking too long. Will let you know once I have a branch up for it.

**Comment by lavajuno** [comment]
Merged into main, if you have any issues just let me know.

**Comment by PFython** [comment]
Fantastic, many thanks!

I've submitted a mini pull request for your consideration, mainly internalising .encode/.decode and renaming with friendly .load and .save methods.

https://github.com/lavajuno/afskmodem/pull/10
